config/routes.rb
Medicos::Application.routes.draw do
  resources :medicos

  resources :especialidads

  

end

app/models/especialidad.rb
class Especialidad < ActiveRecord::Base
end

app/models/medico.rb
class Medico < ActiveRecord::Base
  belongs_to :especialidad
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/especialidads_controller.rb
class EspecialidadsController < ApplicationController
  before_action :set_especialidad, only: [:show, :edit, :update, :destroy]

  # GET /especialidads
  # GET /especialidads.json
  def index
    @especialidads = Especialidad.all
  end

  # GET /especialidads/1
  # GET /especialidads/1.json
  def show
  end

  # GET /especialidads/new
  def new
    @especialidad = Especialidad.new
  end

  # GET /especialidads/1/edit
  def edit
  end

  # POST /especialidads
  # POST /especialidads.json
  def create
    @especialidad = Especialidad.new(especialidad_params)

    respond_to do |format|
      if @especialidad.save
        format.html { redirect_to @especialidad, notice: 'Especialidad was successfully created.' }
        format.json { render action: 'show', status: :created, location: @especialidad }
      else
        format.html { render action: 'new' }
        format.json { render json: @especialidad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /especialidads/1
  # PATCH/PUT /especialidads/1.json
  def update
    respond_to do |format|
      if @especialidad.update(especialidad_params)
        format.html { redirect_to @especialidad, notice: 'Especialidad was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @especialidad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /especialidads/1
  # DELETE /especialidads/1.json
  def destroy
    @especialidad.destroy
    respond_to do |format|
      format.html { redirect_to especialidads_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_especialidad
      @especialidad = Especialidad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def especialidad_params
      params.require(:especialidad).permit(:nombre)
    end
end

app/controllers/medicos_controller.rb
class MedicosController < ApplicationController
  before_action :set_medico, only: [:show, :edit, :update, :destroy]

  # GET /medicos
  # GET /medicos.json
  def index
    @medicos = Medico.all
  end

  # GET /medicos/1
  # GET /medicos/1.json
  def show
  end

  # GET /medicos/new
  def new
    @medico = Medico.new
  end

  # GET /medicos/1/edit
  def edit
  end

  # POST /medicos
  # POST /medicos.json
  def create
    @medico = Medico.new(medico_params)

    respond_to do |format|
      if @medico.save
        format.html { redirect_to @medico, notice: 'Medico was successfully created.' }
        format.json { render action: 'show', status: :created, location: @medico }
      else
        format.html { render action: 'new' }
        format.json { render json: @medico.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medicos/1
  # PATCH/PUT /medicos/1.json
  def update
    respond_to do |format|
      if @medico.update(medico_params)
        format.html { redirect_to @medico, notice: 'Medico was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @medico.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medicos/1
  # DELETE /medicos/1.json
  def destroy
    @medico.destroy
    respond_to do |format|
      format.html { redirect_to medicos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medico
      @medico = Medico.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def medico_params
      params.require(:medico).permit(:nombres, :apellidos, :celular, :email, :curriculum, :reconocimiento, :imagen, :especialidad_id, :especialidad_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/especialidads_helper.rb
module EspecialidadsHelper
end

app/helpers/medicos_helper.rb
module MedicosHelper
end

app/views/especialidads/_form.html.erb
<%= form_for(@especialidad) do |f| %>
  <% if @especialidad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@especialidad.errors.count, "error") %> prohibited this especialidad from being saved:</h2>

      <ul>
      <% @especialidad.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/especialidads/edit.html.erb
<h1>Editing especialidad</h1>

<%= render 'form' %>

<%= link_to 'Show', @especialidad %> |
<%= link_to 'Back', especialidads_path %>

app/views/especialidads/index.html.erb
<h1>Listing especialidads</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @especialidads.each do |especialidad| %>
      <tr>
        <td><%= especialidad.nombre %></td>
        <td><%= link_to 'Show', especialidad %></td>
        <td><%= link_to 'Edit', edit_especialidad_path(especialidad) %></td>
        <td><%= link_to 'Destroy', especialidad, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Especialidad', new_especialidad_path %>

app/views/especialidads/new.html.erb
<h1>New especialidad</h1>

<%= render 'form' %>

<%= link_to 'Back', especialidads_path %>

app/views/especialidads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @especialidad.nombre %>
</p>

<%= link_to 'Edit', edit_especialidad_path(@especialidad) %> |
<%= link_to 'Back', especialidads_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Medicos</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/medicos/_form.html.erb
<%= form_for(@medico) do |f| %>
  <% if @medico.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@medico.errors.count, "error") %> prohibited this medico from being saved:</h2>

      <ul>
      <% @medico.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombres %><br>
    <%= f.text_field :nombres %>
  </div>
  <div class="field">
    <%= f.label :apellidos %><br>
    <%= f.text_field :apellidos %>
  </div>
  <div class="field">
    <%= f.label :celular %><br>
    <%= f.text_field :celular %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :curriculum %><br>
    <%= f.text_area :curriculum %>
  </div>
  <div class="field">
    <%= f.label :reconocimiento %><br>
    <%= f.text_field :reconocimiento %>
  </div>
  <div class="field">
    <%= f.label :imagen %><br>
    <%= f.text_field :imagen %>
  </div>
  <div class="field">
    <%= f.label :especialidad %><br>
    <%= f.text_field :especialidad %>
  </div>
  <div class="field">
    <%= f.label :especialidad_id %><br>
    <%= f.number_field :especialidad_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/medicos/edit.html.erb
<h1>Editing medico</h1>

<%= render 'form' %>

<%= link_to 'Show', @medico %> |
<%= link_to 'Back', medicos_path %>

app/views/medicos/index.html.erb
<h1>Listing medicos</h1>

<table>
  <thead>
    <tr>
      <th>Nombres</th>
      <th>Apellidos</th>
      <th>Celular</th>
      <th>Email</th>
      <th>Curriculum</th>
      <th>Reconocimiento</th>
      <th>Imagen</th>
      <th>Especialidad</th>
      <th>Especialidad</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @medicos.each do |medico| %>
      <tr>
        <td><%= medico.nombres %></td>
        <td><%= medico.apellidos %></td>
        <td><%= medico.celular %></td>
        <td><%= medico.email %></td>
        <td><%= medico.curriculum %></td>
        <td><%= medico.reconocimiento %></td>
        <td><%= medico.imagen %></td>
        <td><%= medico.especialidad %></td>
        <td><%= medico.especialidad_id %></td>
        <td><%= link_to 'Show', medico %></td>
        <td><%= link_to 'Edit', edit_medico_path(medico) %></td>
        <td><%= link_to 'Destroy', medico, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Medico', new_medico_path %>

app/views/medicos/new.html.erb
<h1>New medico</h1>

<%= render 'form' %>

<%= link_to 'Back', medicos_path %>

app/views/medicos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombres:</strong>
  <%= @medico.nombres %>
</p>

<p>
  <strong>Apellidos:</strong>
  <%= @medico.apellidos %>
</p>

<p>
  <strong>Celular:</strong>
  <%= @medico.celular %>
</p>

<p>
  <strong>Email:</strong>
  <%= @medico.email %>
</p>

<p>
  <strong>Curriculum:</strong>
  <%= @medico.curriculum %>
</p>

<p>
  <strong>Reconocimiento:</strong>
  <%= @medico.reconocimiento %>
</p>

<p>
  <strong>Imagen:</strong>
  <%= @medico.imagen %>
</p>

<p>
  <strong>Especialidad:</strong>
  <%= @medico.especialidad %>
</p>

<p>
  <strong>Especialidad:</strong>
  <%= @medico.especialidad_id %>
</p>

<%= link_to 'Edit', edit_medico_path(@medico) %> |
<%= link_to 'Back', medicos_path %>